/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BecomeOrganizerRouteImport } from './routes/become-organizer'
import { Route as OrganizerLayoutRouteImport } from './routes/organizer/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as PageRouteImport } from './routes/page'
import { Route as OrganizerDashboardRouteImport } from './routes/organizer/dashboard'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as OrganizerEventsPageRouteImport } from './routes/organizer/events/page'
import { Route as OrganizerEventsIdCreateEventRouteImport } from './routes/organizer/events/$id/create-event'

const BecomeOrganizerRoute = BecomeOrganizerRouteImport.update({
  id: '/become-organizer',
  path: '/become-organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerLayoutRoute = OrganizerLayoutRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerDashboardRoute = OrganizerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)
const OrganizerEventsPageRoute = OrganizerEventsPageRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => OrganizerLayoutRoute,
} as any)
const OrganizerEventsIdCreateEventRoute =
  OrganizerEventsIdCreateEventRouteImport.update({
    id: '/events/$id/create-event',
    path: '/events/$id/create-event',
    getParentRoute: () => OrganizerLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/organizer': typeof OrganizerLayoutRouteWithChildren
  '/become-organizer': typeof BecomeOrganizerRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/events': typeof OrganizerEventsPageRoute
  '/organizer/events/$id/create-event': typeof OrganizerEventsIdCreateEventRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/organizer': typeof OrganizerLayoutRouteWithChildren
  '/become-organizer': typeof BecomeOrganizerRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/events': typeof OrganizerEventsPageRoute
  '/organizer/events/$id/create-event': typeof OrganizerEventsIdCreateEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/(auth)': typeof authLayoutRouteWithChildren
  '/organizer': typeof OrganizerLayoutRouteWithChildren
  '/become-organizer': typeof BecomeOrganizerRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/events/': typeof OrganizerEventsPageRoute
  '/organizer/events/$id/create-event': typeof OrganizerEventsIdCreateEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizer'
    | '/become-organizer'
    | '/sign-in'
    | '/sign-up'
    | '/organizer/dashboard'
    | '/organizer/events'
    | '/organizer/events/$id/create-event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organizer'
    | '/become-organizer'
    | '/sign-in'
    | '/sign-up'
    | '/organizer/dashboard'
    | '/organizer/events'
    | '/organizer/events/$id/create-event'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/organizer'
    | '/become-organizer'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/organizer/dashboard'
    | '/organizer/events/'
    | '/organizer/events/$id/create-event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  OrganizerLayoutRoute: typeof OrganizerLayoutRouteWithChildren
  BecomeOrganizerRoute: typeof BecomeOrganizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/become-organizer': {
      id: '/become-organizer'
      path: '/become-organizer'
      fullPath: '/become-organizer'
      preLoaderRoute: typeof BecomeOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/dashboard': {
      id: '/organizer/dashboard'
      path: '/dashboard'
      fullPath: '/organizer/dashboard'
      preLoaderRoute: typeof OrganizerDashboardRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/organizer/events/': {
      id: '/organizer/events/'
      path: '/events'
      fullPath: '/organizer/events'
      preLoaderRoute: typeof OrganizerEventsPageRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
    '/organizer/events/$id/create-event': {
      id: '/organizer/events/$id/create-event'
      path: '/events/$id/create-event'
      fullPath: '/organizer/events/$id/create-event'
      preLoaderRoute: typeof OrganizerEventsIdCreateEventRouteImport
      parentRoute: typeof OrganizerLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface OrganizerLayoutRouteChildren {
  OrganizerDashboardRoute: typeof OrganizerDashboardRoute
  OrganizerEventsPageRoute: typeof OrganizerEventsPageRoute
  OrganizerEventsIdCreateEventRoute: typeof OrganizerEventsIdCreateEventRoute
}

const OrganizerLayoutRouteChildren: OrganizerLayoutRouteChildren = {
  OrganizerDashboardRoute: OrganizerDashboardRoute,
  OrganizerEventsPageRoute: OrganizerEventsPageRoute,
  OrganizerEventsIdCreateEventRoute: OrganizerEventsIdCreateEventRoute,
}

const OrganizerLayoutRouteWithChildren = OrganizerLayoutRoute._addFileChildren(
  OrganizerLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  OrganizerLayoutRoute: OrganizerLayoutRouteWithChildren,
  BecomeOrganizerRoute: BecomeOrganizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
